<div style="font-family: 'Times New Roman', serif; font-size: 18px; line-height: 1.6;">

  <h1 style="color: #006699; font-weight: bold;">SQL in Python: Notes and Examples </h1>

  <h2 style="color: #006699;">Introduction</h2>
  <p>
    <strong>SQL (Structured Query Language)</strong> is used to create, retrieve,
    update, and delete data in relational databases. Combining SQL with Python
    supports data analysis, visualization, and automated reporting.
  </p>

  <h2 style="color: #006699;">What Is SQLite?</h2>
  <p>
    <strong>SQLite</strong> is a lightweight database that stores everything in a
    single file and requires no separate server. Python's <strong>sqlite3</strong>
    module connects to it and runs SQL commands.
  </p>

  <h2 style="color: #006699;">Datasets used in this notebook</h2>
  <table style="border-collapse: collapse; font-size: 16px;">
    <tr style="background: #e8f0f5;"><th style="padding: 6px 12px; text-align: left;">Concept</th><th style="padding: 6px 12px; text-align: left;">Sector</th><th style="padding: 6px 12px; text-align: left;">File</th></tr>
    <tr><td style="padding: 4px 12px;">SELECT</td><td style="padding: 4px 12px;">Retail</td><td style="padding: 4px 12px;">sales.csv</td></tr>
    <tr><td style="padding: 4px 12px;">WHERE</td><td style="padding: 4px 12px;">Human Resources</td><td style="padding: 4px 12px;">hr_employees.csv</td></tr>
    <tr><td style="padding: 4px 12px;">ORDER BY</td><td style="padding: 4px 12px;">Real Estate</td><td style="padding: 4px 12px;">realestate_listings.csv</td></tr>
    <tr><td style="padding: 4px 12px;">GROUP BY</td><td style="padding: 4px 12px;">Marketing</td><td style="padding: 4px 12px;">marketing_campaigns.csv</td></tr>
    <tr><td style="padding: 4px 12px;">HAVING</td><td style="padding: 4px 12px;">Restaurant</td><td style="padding: 4px 12px;">restaurant_orders.csv</td></tr>
    <tr><td style="padding: 4px 12px;">JOIN</td><td style="padding: 4px 12px;">Banking</td><td style="padding: 4px 12px;">bank_customers.csv, bank_transactions.csv</td></tr>
    <tr><td style="padding: 4px 12px;">Aggregate functions</td><td style="padding: 4px 12px;">Healthcare</td><td style="padding: 4px 12px;">clinic_visits.csv</td></tr>
  </table>
  <p>Place all CSV files in the same folder as this notebook.</p>

</div>

In [1]:
# sqlite3 provides tools for connecting to SQLite databases.
import sqlite3
# pandas works with tables; pd is its short name.
import pandas as pd

# Connect to the database (creates the file if it doesn't exist)
conn = sqlite3.connect('my_data.db')

# Create a cursor object to execute SQL commands
cursor = conn.cursor()

<div style="font-family: 'Times New Roman', serif; font-size: 18px; line-height: 1.6;">

  <h2 style="color: #006699; font-weight: bold;">SELECT</h2>

  <h3 style="color: #006699;">Definition</h3>
  <p><strong>SELECT</strong> retrieves data from a table. Name the columns to retrieve, or use <code>*</code> to retrieve all columns.</p>

  <h3 style="color: #006699;">Syntax</h3>
  <pre style="background: #f4f4f4; padding: 10px; border-left: 4px solid #006699;">
SELECT column1, column2 FROM table_name;
SELECT * FROM table_name;        -- * means all columns</pre>

  <h3 style="color: #006699;">Task: Read a CSV File</h3>
  <p>Read <strong>sales.csv</strong> into a pandas DataFrame and save it as a database table named <strong>sales</strong>.</p>

  <h3 style="color: #006699;">What This Task Does</h3>
  <ul>
    <li>Reads the CSV file using <code>pd.read_csv()</code>.</li>
    <li>Saves the data to the database using <code>to_sql()</code>.</li>
    <li>Retrieves all columns or selected columns using <code>SELECT</code>.</li>
  </ul>

  <h3 style="color: #006699;">Examples</h3>
  <ul>
    <li><strong>Example 1: All columns:</strong> <code>SELECT * FROM sales;</code></li>
    <li><strong>Example 2: Selected columns:</strong> <code>SELECT product, region, quantity FROM sales;</code></li>
  </ul>

</div>

In [2]:
# read_csv() reads a CSV file into a pandas table.
# to_sql() copies the table into the connected database.
# if_exists="replace" replaces the existing table with the CSV data.
# index=False avoids saving the pandas row index as a column.
# Load sales.csv into the 'sales' table
pd.read_csv('sales.csv').to_sql('sales', conn, if_exists='replace', index=False)

20

In [3]:
# read_sql_query() runs SQL and returns the results as a pandas DataFrame.
# Triple quotation marks allow SQL to span several lines.
# conn identifies the database connection.
# SELECT * returns every column.
# Example 1: All columns
pd.read_sql_query('''
SELECT * FROM sales
''', conn)

    sale_id  sale_date     product     category region  quantity   price
0         1   9/1/2026      Laptop  Electronics   East         2  999.99
1         2   9/1/2026       Mouse  Accessories   East        10   24.99
2         3   9/2/2026     Monitor  Electronics   West         3  199.99
3         4   9/2/2026    Keyboard  Accessories  North         4   49.99
4         5   9/3/2026      Laptop  Electronics   West         1  999.99
5         6   9/3/2026  Headphones  Accessories  South         6   79.99
6         7   9/4/2026       Mouse  Accessories  North         5   24.99
7         8   9/4/2026     Monitor  Electronics   East         2  199.99
8         9   9/5/2026      Laptop  Electronics  South         3  999.99
9        10   9/5/2026    Keyboard  Accessories   West         7   49.99
10       11   9/6/2026  Headphones  Accessories   East         4   79.99
11       12   9/6/2026      Tablet  Electronics  North         2  449.99
12       13   9/7/2026       Mouse  Accessories  South         8   24.99
13       14   9/7/2026      Tablet  Electronics   West         1  449.99
14       15   9/8/2026     Monitor  Electronics  North         2  199.99
15       16   9/8/2026      Laptop  Electronics   East         1  999.99
16       17   9/9/2026    Keyboard  Accessories  South         3   49.99
17       18   9/9/2026  Headphones  Accessories   West         5   79.99
18       19  9/10/2026      Tablet  Electronics   East         3  449.99
19       20  9/10/2026       Mouse  Accessories   West        12   24.99

In [4]:
# read_sql_query() runs SQL and returns the results as a pandas DataFrame.
# Triple quotation marks allow SQL to span several lines.
# conn identifies the database connection.
# Example 2: Only the columns you need
pd.read_sql_query('''
SELECT product, region, quantity FROM sales
''', conn)

       product region  quantity
0       Laptop   East         2
1        Mouse   East        10
2      Monitor   West         3
3     Keyboard  North         4
4       Laptop   West         1
5   Headphones  South         6
6        Mouse  North         5
7      Monitor   East         2
8       Laptop  South         3
9     Keyboard   West         7
10  Headphones   East         4
11      Tablet  North         2
12       Mouse  South         8
13      Tablet   West         1
14     Monitor  North         2
15      Laptop   East         1
16    Keyboard  South         3
17  Headphones   West         5
18      Tablet   East         3
19       Mouse   West        12

<div style="font-family: 'Times New Roman', serif; font-size: 18px; line-height: 1.6;">
  <h3 style="color: #006699; font-weight: bold;">Student Practice</h3>
  <ol>
    <li>Retrieve only <strong>sale_date</strong>, <strong>product</strong>, and <strong>price</strong> from the <strong>sales</strong> table.</li>
    <li>Use <strong>SELECT</strong> to specify these three columns.</li>
    <li>Run the query using <code>pd.read_sql_query()</code> and the existing connection <code>conn</code>.</li>
    <li>Check that the output displays all sales records with only the three requested columns.</li>
  </ol>
</div>

<div style="font-family: 'Times New Roman', serif; font-size: 18px; line-height: 1.6;">

  <h2 style="color: #006699; font-weight: bold;">WHERE</h2>

  <h3 style="color: #006699;">Definition</h3>
  <p><strong>WHERE</strong> filters rows. Only rows that meet the condition are returned. The data in the database remains unchanged.</p>

  <h3 style="color: #006699;">Syntax</h3>
  <pre style="background: #f4f4f4; padding: 10px; border-left: 4px solid #006699;">
SELECT columns FROM table_name WHERE condition;

-- Comparison: =   &gt;   &lt;   &gt;=   &lt;=   &lt;&gt;  (not equal)
-- Combine: AND   OR
-- Text values go in quotes: 'Sales'
-- Numbers do not: 60000</pre>

  <h3 style="color: #006699;">Task: Read a CSV File</h3>
  <p>Read <strong>hr_employees.csv</strong> into a pandas DataFrame and save it as a database table named <strong>employees</strong>.</p>

  <h3 style="color: #006699;">What This Task Does</h3>
  <ul>
    <li>Reads employee records using <code>pd.read_csv()</code>.</li>
    <li>Saves the data to the database using <code>to_sql()</code>.</li>
    <li>Filters employees by department, salary, and employment status using <code>WHERE</code>.</li>
  </ul>

  <h3 style="color: #006699;">Examples</h3>
  <ul>
    <li><strong>Example 1: Filter on text:</strong> <code>SELECT name, department, salary FROM employees WHERE department = 'Sales';</code></li>
    <li><strong>Example 2: Filter on a number with AND:</strong> <code>SELECT name, city, salary FROM employees WHERE salary &gt; 80000 AND full_time = 'Yes';</code></li>
  </ul>

</div>

In [6]:
# read_csv() reads a CSV file into a pandas table.
# to_sql() copies the table into the connected database.
# if_exists="replace" replaces the existing table with the CSV data.
# index=False avoids saving the pandas row index as a column.
# Load hr_employees.csv into the 'employees' table
pd.read_csv('hr_employees.csv').to_sql('employees', conn, if_exists='replace', index=False)

30

In [7]:
# read_sql_query() runs SQL and returns the results as a pandas DataFrame.
# Triple quotation marks allow SQL to span several lines.
# conn identifies the database connection.
# WHERE keeps rows that meet the condition.
# Example 1: Filter on text
pd.read_sql_query('''
SELECT name, department, salary
FROM employees
WHERE department = 'Sales'
''', conn)

       name department  salary
0  Isabella      Sales   86000
1     Lucas      Sales  110000
2       Mia      Sales   79000

In [8]:
# read_sql_query() runs SQL and returns the results as a pandas DataFrame.
# Triple quotation marks allow SQL to span several lines.
# conn identifies the database connection.
# WHERE keeps rows that meet the condition.
# Example 2: Filter on a number with AND
pd.read_sql_query('''
SELECT name, city, salary
FROM employees
WHERE salary > 80000 AND full_time = 'Yes'
''', conn)

       name     city  salary
0      Noah   Dallas  106000
1       Ava   Dallas  111000
2    Sophia  Atlanta   85000
3  Isabella   Denver   86000
4     James  Atlanta  123000
5  Benjamin   Dallas  110000
6     Grace  Atlanta   88000
7     Chloe   Dallas   96000
8    Carter  Atlanta  118000
9    Julian  Chicago  122000

<div style="font-family: 'Times New Roman', serif; font-size: 18px; line-height: 1.6;">
  <h3 style="color: #006699; font-weight: bold;">Student Practice</h3>
  <ol>
    <li>Read <strong>hr_employees.csv</strong> using <code>pd.read_csv()</code> and save the data as the <strong>employees</strong> database table using <code>to_sql()</code> and the existing connection <code>conn</code>.</li>
    <li>Retrieve all columns for employees in <strong>Chicago</strong> who have more than <strong>10 years of experience</strong>.</li>
    <li>Use <strong>SELECT *</strong> to display all columns and <strong>WHERE</strong> with <strong>AND</strong> to apply both conditions: <code>city = 'Chicago'</code> and <code>years_experience &gt; 10</code>.</li>
    <li>Run the query using <code>pd.read_sql_query()</code> with <code>conn</code> and display the result.</li>
    <li>Check that every employee in the output is based in Chicago and has more than 10 years of experience.</li>
  </ol>
</div>

<div style="font-family: 'Times New Roman', serif; font-size: 18px; line-height: 1.6;">

  <h2 style="color: #006699; font-weight: bold;">ORDER BY</h2>

  <h3 style="color: #006699;">Definition</h3>
  <p><strong>ORDER BY</strong> sorts the results. <code>ASC</code> sorts from lowest to highest (the default); <code>DESC</code> sorts from highest to lowest. Add <code>LIMIT</code> to return only a specified number of rows.</p>

  <h3 style="color: #006699;">Syntax</h3>
  <pre style="background: #f4f4f4; padding: 10px; border-left: 4px solid #006699;">
SELECT columns FROM table_name ORDER BY column ASC;
SELECT columns FROM table_name ORDER BY column DESC LIMIT 5;</pre>

  <h3 style="color: #006699;">Task: Read a CSV File</h3>
  <p>Read <strong>realestate_listings.csv</strong> into a pandas DataFrame and save it as a database table named <strong>listings</strong>.</p>

  <h3 style="color: #006699;">What This Task Does</h3>
  <ul>
    <li>Reads property listings using <code>pd.read_csv()</code>.</li>
    <li>Saves the data to the database using <code>to_sql()</code>.</li>
    <li>Sorts properties by price using <code>ORDER BY</code>.</li>
    <li>Displays five listings with the fewest days on the market using <code>ORDER BY</code> and <code>LIMIT</code>.</li>
  </ul>

  <h3 style="color: #006699;">Examples</h3>
  <ul>
    <li><strong>Example 1: Most expensive first:</strong> <code>SELECT neighborhood, property_type, list_price FROM listings ORDER BY list_price DESC;</code></li>
    <li><strong>Example 2: Five newest listings:</strong> <code>SELECT listing_id, neighborhood, days_on_market FROM listings ORDER BY days_on_market ASC LIMIT 5;</code></li>
  </ul>

</div>

In [10]:
# read_csv() reads a CSV file into a pandas table.
# to_sql() copies the table into the connected database.
# if_exists="replace" replaces the existing table with the CSV data.
# index=False avoids saving the pandas row index as a column.
# Load realestate_listings.csv into the 'listings' table
pd.read_csv('realestate_listings.csv').to_sql('listings', conn, if_exists='replace', index=False)

25

In [11]:
# read_sql_query() runs SQL and returns the results as a pandas DataFrame.
# Triple quotation marks allow SQL to span several lines.
# conn identifies the database connection.
# ORDER BY sorts results; ASC is ascending and DESC is descending.
# Example 1: Most expensive first
pd.read_sql_query('''
SELECT neighborhood, property_type, list_price
FROM listings
ORDER BY list_price DESC
''', conn)

   neighborhood property_type  list_price
0   Maple Grove         Condo     1001000
1     Riverside         Condo      979000
2   Maple Grove         House      661000
3      Oak Park     Apartment      661000
4     Hillcrest         House      603000
5   Maple Grove     Apartment      583000
6     Riverside         House      561000
7     Riverside     Apartment      537000
8     Riverside         House      536000
9      Lakeview     Apartment      528000
10     Downtown         Condo      496000
11    Hillcrest         Condo      477000
12     Lakeview     Apartment      408000
13     Downtown         Condo      385000
14     Downtown         House      361000
15     Downtown         House      360000
16     Downtown         House      315000
17    Hillcrest     Apartment      296000
18     Lakeview         Condo      271000
19     Downtown     Apartment      266000
20    Hillcrest     Townhouse      242000
21    Riverside     Apartment      240000
22     Lakeview         House      232000
23     Oak Park     Townhouse      201000
24    Riverside     Apartment      126000

In [12]:
# read_sql_query() runs SQL and returns the results as a pandas DataFrame.
# Triple quotation marks allow SQL to span several lines.
# conn identifies the database connection.
# ORDER BY sorts results; ASC is ascending and DESC is descending.
# LIMIT restricts the number of returned rows.
# Example 2: Five newest listings
pd.read_sql_query('''
SELECT listing_id, neighborhood, days_on_market
FROM listings
ORDER BY days_on_market ASC
LIMIT 5
''', conn)

   listing_id neighborhood  days_on_market
0         208     Downtown               1
1         225     Lakeview               6
2         222     Lakeview               8
3         214    Hillcrest              14
4         215    Riverside              24

<div style="font-family: 'Times New Roman', serif; font-size: 18px; line-height: 1.6;">
  <h3 style="color: #006699; font-weight: bold;">Student Practice</h3>
  <ol>
    <li>Read <strong>realestate_listings.csv</strong> using <code>pd.read_csv()</code> and save the data as the <strong>listings</strong> database table using <code>to_sql()</code> and the existing connection <code>conn</code>.</li>
    <li>Retrieve all columns for the <strong>three largest properties</strong> based on <strong>sqft</strong>.</li>
    <li>Use <strong>SELECT *</strong> to display all columns, <code>ORDER BY sqft DESC</code> to sort from largest to smallest, and <code>LIMIT 3</code> to return only three properties.</li>
    <li>Run the query using <code>pd.read_sql_query()</code> with <code>conn</code> and display the result.</li>
    <li>Check that the output shows the three largest properties, ordered from largest to smallest by square footage.</li>
  </ol>
</div>

<div style="font-family: 'Times New Roman', serif; font-size: 18px; line-height: 1.6;">

  <h2 style="color: #006699; font-weight: bold;">GROUP BY</h2>

  <h3 style="color: #006699;">Definition</h3>
  <p><strong>GROUP BY</strong> groups rows with matching values so that each group can be summarized. Similar to an Excel PivotTable, it is commonly used with aggregate functions such as <code>SUM</code> or <code>COUNT</code>.</p>

  <h3 style="color: #006699;">Syntax</h3>
  <pre style="background: #f4f4f4; padding: 10px; border-left: 4px solid #006699;">
SELECT group_column, SUM(value_column) AS total
FROM table_name
GROUP BY group_column;</pre>

  <h3 style="color: #006699;">Task: Read a CSV File</h3>
  <p>Read <strong>marketing_campaigns.csv</strong> into a pandas DataFrame and save it as a database table named <strong>campaigns</strong>.</p>

  <h3 style="color: #006699;">What This Task Does</h3>
  <ul>
    <li>Reads campaign records using <code>pd.read_csv()</code>.</li>
    <li>Saves the data to the database using <code>to_sql()</code>.</li>
    <li>Calculates total spending by marketing channel using <code>GROUP BY</code> and <code>SUM()</code>.</li>
    <li>Summarizes clicks and conversions by campaign and sorts by total conversions.</li>
  </ul>

  <h3 style="color: #006699;">Examples</h3>
  <ul>
    <li><strong>Example 1: Total spend by channel:</strong> <code>SELECT channel, SUM(spend) AS total_spend FROM campaigns GROUP BY channel;</code></li>
    <li><strong>Example 2: Clicks and conversions by campaign:</strong> <code>SELECT campaign, SUM(clicks) AS total_clicks, SUM(conversions) AS total_conversions FROM campaigns GROUP BY campaign ORDER BY total_conversions DESC;</code></li>
  </ul>

</div>

In [13]:
# read_csv() reads a CSV file into a pandas table.
# to_sql() copies the table into the connected database.
# if_exists="replace" replaces the existing table with the CSV data.
# index=False avoids saving the pandas row index as a column.
# Load marketing_campaigns.csv into the 'campaigns' table
pd.read_csv('marketing_campaigns.csv').to_sql('campaigns', conn, if_exists='replace', index=False)

40

In [14]:
# read_sql_query() runs SQL and returns the results as a pandas DataFrame.
# Triple quotation marks allow SQL to span several lines.
# conn identifies the database connection.
# GROUP BY combines records into groups for summary calculations.
# SUM() adds values.
# AS gives a result column or table a short name.
# Example 1: Total spend by channel
pd.read_sql_query('''
SELECT channel, SUM(spend) AS total_spend
FROM campaigns
GROUP BY channel
''', conn)

        channel  total_spend
0   Display Ads     21046.26
1         Email      4679.08
2    Influencer     23933.69
3    Search Ads     17873.55
4  Social Media     16904.67

In [15]:
# read_sql_query() runs SQL and returns the results as a pandas DataFrame.
# Triple quotation marks allow SQL to span several lines.
# conn identifies the database connection.
# ORDER BY sorts results; ASC is ascending and DESC is descending.
# GROUP BY combines records into groups for summary calculations.
# SUM() adds values.
# AS gives a result column or table a short name.
# Example 2: Clicks and conversions by campaign
pd.read_sql_query('''
SELECT campaign,
       SUM(clicks) AS total_clicks,
       SUM(conversions) AS total_conversions
FROM campaigns
GROUP BY campaign
ORDER BY total_conversions DESC
''', conn)

         campaign  total_clicks  total_conversions
0   Summer Launch         16968               1281
1   Holiday Promo         13642               1088
2     Spring Sale         14751               1073
3  Back to School          9453                781

<div style="font-family: 'Times New Roman', serif; font-size: 18px; line-height: 1.6;">
  <h3 style="color: #006699; font-weight: bold;">Student Practice</h3>
  <ol>
    <li>Read <strong>marketing_campaigns.csv</strong> using <code>pd.read_csv()</code> and save the data as the <strong>campaigns</strong> database table using <code>to_sql()</code> and the existing connection <code>conn</code>.</li>
    <li>Calculate the total <strong>impressions</strong> for each <strong>week</strong>.</li>
    <li>Use <strong>SELECT</strong> to retrieve <code>week</code> and <code>SUM(impressions) AS total_impressions</code>. Use <code>GROUP BY week</code> to summarize the records by week.</li>
    <li>Run the query using <code>pd.read_sql_query()</code> with <code>conn</code> and display the result.</li>
    <li>Check that the output contains one row per week, showing the week and its total impressions.</li>
  </ol>
</div>

<div style="font-family: 'Times New Roman', serif; font-size: 18px; line-height: 1.6;">

  <h2 style="color: #006699; font-weight: bold;">HAVING</h2>

  <h3 style="color: #006699;">Definition</h3>
  <p><strong>HAVING</strong> filters groups after <code>GROUP BY</code>. Use <code>WHERE</code> for conditions on individual rows and <code>HAVING</code> for conditions on totals, counts, or averages.</p>

  <h3 style="color: #006699;">Syntax</h3>
  <pre style="background: #f4f4f4; padding: 10px; border-left: 4px solid #006699;">
SELECT group_column, SUM(value_column) AS total
FROM table_name
GROUP BY group_column
HAVING SUM(value_column) &gt; 100;</pre>

  <h3 style="color: #006699;">Task: Read a CSV File</h3>
  <p>Read <strong>restaurant_orders.csv</strong> into a pandas DataFrame and save it as a database table named <strong>orders</strong>.</p>

  <h3 style="color: #006699;">What This Task Does</h3>
  <ul>
    <li>Reads restaurant orders using <code>pd.read_csv()</code>.</li>
    <li>Saves the data to the database using <code>to_sql()</code>.</li>
    <li>Groups records by server or menu item using <code>GROUP BY</code>.</li>
    <li>Filters groups by total tips or number of orders using <code>HAVING</code>.</li>
  </ul>

  <h3 style="color: #006699;">Examples</h3>
  <ul>
    <li><strong>Example 1: Servers with more than $130 in tips:</strong> <code>SELECT server, SUM(tip) AS total_tips FROM orders GROUP BY server HAVING SUM(tip) &gt; 130;</code></li>
    <li><strong>Example 2: Menu items ordered at least 6 times:</strong> <code>SELECT menu_item, COUNT(*) AS times_ordered FROM orders GROUP BY menu_item HAVING COUNT(*) &gt;= 6;</code></li>
  </ul>

</div>

In [16]:
# read_csv() reads a CSV file into a pandas table.
# to_sql() copies the table into the connected database.
# if_exists="replace" replaces the existing table with the CSV data.
# index=False avoids saving the pandas row index as a column.
# Load restaurant_orders.csv into the 'orders' table
pd.read_csv('restaurant_orders.csv').to_sql('orders', conn, if_exists='replace', index=False)

50

In [17]:
# read_sql_query() runs SQL and returns the results as a pandas DataFrame.
# Triple quotation marks allow SQL to span several lines.
# conn identifies the database connection.
# GROUP BY combines records into groups for summary calculations.
# HAVING keeps groups that meet the aggregate condition.
# SUM() adds values.
# ROUND(value, digits) rounds a number to the specified decimal places.
# AS gives a result column or table a short name.
# Example 1: Servers with more than $130 in tips
pd.read_sql_query('''
SELECT server, ROUND(SUM(tip), 2) AS total_tips
FROM orders
GROUP BY server
HAVING SUM(tip) > 130
''', conn)

  server  total_tips
0  Priya      155.21
1   Tina      133.49

In [18]:
# read_sql_query() runs SQL and returns the results as a pandas DataFrame.
# Triple quotation marks allow SQL to span several lines.
# conn identifies the database connection.
# GROUP BY combines records into groups for summary calculations.
# HAVING keeps groups that meet the aggregate condition.
# COUNT(*) counts rows.
# AS gives a result column or table a short name.
# Example 2: Menu items ordered at least 6 times
pd.read_sql_query('''
SELECT menu_item, COUNT(*) AS times_ordered
FROM orders
GROUP BY menu_item
HAVING COUNT(*) >= 6
''', conn)

  menu_item  times_ordered
0     Pizza              6
1     Salad              8
2     Wings             10

<div style="font-family: 'Times New Roman', serif; font-size: 18px; line-height: 1.6;">
  <h3 style="color: #006699; font-weight: bold;">Student Practice</h3>

  <p>Read <strong>restaurant_orders.csv</strong> using <code>pd.read_csv()</code> and save the data as the <strong>orders</strong> database table using <code>to_sql()</code> and the existing connection <code>conn</code>.</p>

  <ol>
    <li>Find the dates when total sales exceeded <strong>&#36;400</strong>.</li>
    <li>Run the query using <code>pd.read_sql_query()</code> with <code>conn</code> and display the result.</li>
    <li>Check that the output contains one row per qualifying date and that every total is greater than <strong>&#36;400</strong>.</li>
  </ol>
</div>


<div style="font-family: 'Times New Roman', serif; font-size: 18px; line-height: 1.6;">

  <h2 style="color: #006699; font-weight: bold;">
    Aggregate Functions
  </h2>

  <h3 style="color: #006699;">Definition</h3>
  <p>
    <strong>Aggregate functions</strong> calculate one value
    from many rows:
    <code>SUM()</code> adds,
    <code>COUNT()</code> counts rows,
    <code>AVG()</code> calculates the average,
    <code>MIN()</code> finds the smallest value, and
    <code>MAX()</code> finds the largest value.
    Use <code>ROUND(value, 2)</code> to round decimals.
  </p>

  <h3 style="color: #006699;">Syntax</h3>

  <pre style="background: #f4f4f4; padding: 10px; border-left: 4px solid #006699;">SELECT COUNT(*), SUM(col), AVG(col), MIN(col), MAX(col)
FROM table_name;</pre>

  <p>
    <strong>Note:</strong> GROUP BY produces one summary
    for each group.
  </p>

  <h3 style="color: #006699;">Task: Healthcare</h3>

  <p>
    Read <strong>clinic_visits.csv</strong> using
    <code>pd.read_csv()</code> and save the data as the
    <strong>visits</strong> database table using
    <code>to_sql()</code> and the existing connection
    <code>conn</code>.
  </p>

  <h3 style="color: #006699;">What This Task Does</h3>

  <ul>
    <li>Loads clinic visits into a database table.</li>
    <li>Calculates counts, averages, minimums, and maximums.</li>
    <li>Summarizes clinic performance by department.</li>
  </ul>

  <h3 style="color: #006699;">Examples</h3>

  <p><strong>Example 1: Whole Clinic Summary</strong></p>

  <pre style="background: #f4f4f4; padding: 10px; border-left: 4px solid #006699;">SELECT COUNT(*) AS total_visits,
       AVG(wait_minutes) AS avg_wait,
       MIN(visit_cost) AS lowest_cost,
       MAX(visit_cost) AS highest_cost
FROM visits;</pre>

  <p><strong>Example 2: Summary by Department</strong></p>

  <pre style="background: #f4f4f4; padding: 10px; border-left: 4px solid #006699;">SELECT department,
       COUNT(*) AS visits,
       ROUND(AVG(visit_cost), 2) AS avg_cost
FROM visits
GROUP BY department;</pre>

</div>

In [19]:
# read_csv() reads a CSV file into a pandas table.
# to_sql() copies the table into the connected database.
# if_exists="replace" replaces the existing table with the CSV data.
# index=False avoids saving the pandas row index as a column.
# Load clinic_visits.csv into the 'visits' table
pd.read_csv('clinic_visits.csv').to_sql('visits', conn, if_exists='replace', index=False)

35

In [20]:
# read_sql_query() runs SQL and returns the results as a pandas DataFrame.
# Triple quotation marks allow SQL to span several lines.
# conn identifies the database connection.
# COUNT(*) counts rows.
# AVG() calculates the average of nonmissing values.
# ROUND(value, digits) rounds a number to the specified decimal places.
# MIN() returns the smallest nonmissing value.
# MAX() returns the largest nonmissing value.
# AS gives a result column or table a short name.
# Example 1: Whole clinic summary
pd.read_sql_query('''
SELECT COUNT(*) AS total_visits,
       ROUND(AVG(wait_minutes), 1) AS avg_wait_minutes,
       MIN(visit_cost) AS lowest_cost,
       MAX(visit_cost) AS highest_cost
FROM visits
''', conn)

   total_visits  avg_wait_minutes  lowest_cost  highest_cost
0            35              40.9        89.84        614.04

In [21]:
# read_sql_query() runs SQL and returns the results as a pandas DataFrame.
# Triple quotation marks allow SQL to span several lines.
# conn identifies the database connection.
# GROUP BY combines records into groups for summary calculations.
# COUNT(*) counts rows.
# AVG() calculates the average of nonmissing values.
# ROUND(value, digits) rounds a number to the specified decimal places.
# AS gives a result column or table a short name.
# Example 2: Summary by department
pd.read_sql_query('''
SELECT department,
       COUNT(*) AS visits,
       ROUND(AVG(visit_cost), 2) AS avg_cost
FROM visits
GROUP BY department
''', conn)

    department  visits  avg_cost
0   Cardiology      10    390.94
1  Dermatology       5    284.30
2      General       6    407.75
3  Orthopedics       8    359.49
4   Pediatrics       6    290.70


<div style="font-family: 'Times New Roman', serif; font-size: 18px; line-height: 1.6;">

  <h3 style="color: #006699; font-weight: bold;">
    Student Practice Task: Healthcare
  </h3>

  <p>
    Using the <strong>visits</strong> table, write a SQL query
    to answer the following questions:
  </p>

  <ol>
    <li>Find the average <code>patient_age</code> for each doctor.</li>
    <li>Find the longest <code>wait_minutes</code> for each doctor.</li>
    <li>Use <code>GROUP BY</code> to organize the results by doctor.</li>
    <li>Run the query using <code>pd.read_sql_query()</code> with <code>conn</code>.</li>
    <li>Display the results with one row per doctor.</li>
  </ol>

</div>


<div style="font-family: 'Times New Roman', serif; font-size: 18px; line-height: 1.6;">

  <h2 style="color: #006699; font-weight: bold;">JOIN</h2>

  <h3 style="color: #006699;">Definition</h3>
  <p>
    <strong>JOIN</strong> combines rows from two tables
    using a shared column.
    <code>INNER JOIN</code> keeps only matching rows.
    <code>LEFT JOIN</code> keeps all rows from the left table,
    even when no match exists.
  </p>

  <h3 style="color: #006699;">Syntax</h3>

  <pre style="background: #f4f4f4; padding: 10px; border-left: 4px solid #006699;">SELECT a.column, b.column
FROM table_a AS a
JOIN table_b AS b
ON a.key = b.key;</pre>

  <p>
    <strong>Note:</strong> LEFT JOIN keeps unmatched rows
    from the left table.
  </p>

  <h3 style="color: #006699;">Task: Banking</h3>

  <p>
    Read <strong>bank_customers.csv</strong> using
    <code>pd.read_csv()</code> and save the data as the
    <strong>customers</strong> database table using
    <code>to_sql()</code> and the existing connection
    <code>conn</code>.
  </p>

  <p>
    Read <strong>bank_transactions.csv</strong> using
    <code>pd.read_csv()</code> and save the data as the
    <strong>transactions</strong> database table using
    <code>to_sql()</code> and <code>conn</code>.
  </p>

  <h3 style="color: #006699;">What This Task Does</h3>

  <ul>
    <li>Loads customers and transactions into separate database tables.</li>
    <li>Matches transactions with customer information using <code>customer_id</code>.</li>
    <li>Identifies transactions without matching customers.</li>
  </ul>

  <h3 style="color: #006699;">Examples</h3>

  <p><strong>Example 1: Transactions with Customer Names</strong></p>

  <pre style="background: #f4f4f4; padding: 10px; border-left: 4px solid #006699;">SELECT c.customer_name,
       c.branch,
       t.transaction_type,
       t.amount
FROM transactions AS t
JOIN customers AS c
ON t.customer_id = c.customer_id;</pre>

  <p><strong>Example 2: Transactions Without Matching Customers</strong></p>

  <pre style="background: #f4f4f4; padding: 10px; border-left: 4px solid #006699;">SELECT t.transaction_id,
       t.customer_id,
       c.customer_name,
       t.amount
FROM transactions AS t
LEFT JOIN customers AS c
ON t.customer_id = c.customer_id
WHERE c.customer_id IS NULL;</pre>

</div>

In [22]:
# read_csv() reads a CSV file into a pandas table.
# to_sql() copies the table into the connected database.
# if_exists="replace" replaces the existing table with the CSV data.
# index=False avoids saving the pandas row index as a column.
# Load both files into their own tables
pd.read_csv('bank_customers.csv').to_sql('customers', conn, if_exists='replace', index=False)
pd.read_csv('bank_transactions.csv').to_sql('transactions', conn, if_exists='replace', index=False)

45

In [23]:
# read_sql_query() runs SQL and returns the results as a pandas DataFrame.
# Triple quotation marks allow SQL to span several lines.
# conn identifies the database connection.
# AS gives a result column or table a short name.
# JOIN matches rows from tables using the ON condition.
# Example 1: Transactions with customer names
pd.read_sql_query('''
SELECT c.customer_name, c.branch, t.transaction_type, t.amount
FROM transactions AS t
JOIN customers AS c ON t.customer_id = c.customer_id
''', conn)

   customer_name     branch transaction_type   amount
0     Kai Morgan  Northgate       Withdrawal  2452.32
1       Hana Kim    Main St          Payment   599.23
2     Nia Okafor   Westside         Transfer  1866.87
3      Max Reyes   Westside       Withdrawal  1248.42
4     Ben Carter  Northgate         Transfer  2176.86
5    Omar Haddad    Airport          Payment    58.06
6     Eli Brooks   Westside       Withdrawal   205.57
7    Ivan Petrov   Westside          Payment  1631.59
8     Kai Morgan  Northgate          Payment  2386.27
9     Ben Carter  Northgate          Deposit   602.23
10    Nia Okafor   Westside          Deposit  1120.32
11    Jade Ortiz  Northgate          Deposit   824.45
12    Ben Carter  Northgate         Transfer   949.61
13    Eli Brooks   Westside          Payment  1423.50
14    Fay Nguyen  Northgate       Withdrawal   215.84
15     Max Reyes   Westside       Withdrawal  1254.21
16     Sam Walsh    Airport       Withdrawal  1163.65
17   Ivan Petrov   Westside         Transfer  1673.76
18   Omar Haddad    Airport       Withdrawal   203.18
19  Lena Fischer    Airport         Transfer  1604.57
20    Nia Okafor   Westside         Transfer  1152.95
21    Jade Ortiz  Northgate          Payment  2136.27
22     Dev Patel    Airport          Payment  1438.37
23     Sam Walsh    Airport         Transfer    74.41
24      Pia Lund  Northgate         Transfer  1943.84
25      Hana Kim    Main St         Transfer   563.13
26    Gus Romero    Airport         Transfer  1700.86
27   Omar Haddad    Airport         Transfer  1836.25
28      Cara Liu  Northgate         Transfer  1873.75
29    Fay Nguyen  Northgate       Withdrawal  1970.55
30  Lena Fischer    Airport         Transfer  2079.57
31   Ivan Petrov   Westside          Payment  2419.11
32    Jade Ortiz  Northgate         Transfer  2014.50
33   Omar Haddad    Airport       Withdrawal  1890.30
34      Hana Kim    Main St          Payment  2418.83
35     Rosa Diaz    Airport          Deposit  1980.89
36    Ana Torres    Airport          Deposit  1147.87

In [24]:
# read_sql_query() runs SQL and returns the results as a pandas DataFrame.
# Triple quotation marks allow SQL to span several lines.
# conn identifies the database connection.
# WHERE keeps rows that meet the condition.
# AS gives a result column or table a short name.
# JOIN matches rows from tables using the ON condition.
# LEFT JOIN also keeps rows from the left table without a match.
# IS NULL checks for a missing value.
# Example 2: Transactions with no matching customer (LEFT JOIN)
pd.read_sql_query('''
SELECT t.transaction_id, t.customer_id, c.customer_name, t.amount
FROM transactions AS t
LEFT JOIN customers AS c ON t.customer_id = c.customer_id
WHERE c.customer_name IS NULL
''', conn)

   transaction_id  customer_id customer_name   amount
0           90010           21          None  2183.51
1           90012           22          None  1871.98
2           90027           22          None    40.08
3           90028           22          None  2278.33
4           90032           22          None  1578.06
5           90033           21          None   786.15
6           90044           22          None  1469.71
7           90045           21          None  1693.59


<div style="font-family: 'Times New Roman', serif; font-size: 18px; line-height: 1.6;">

  <h3 style="color: #006699; font-weight: bold;">
    Student Practice Task: Banking
  </h3>

  <p>
    Using the <strong>customers</strong> and
    <strong>transactions</strong> tables, write a SQL query
    to complete the following tasks:
  </p>

  <ol>
    <li>Join both tables using <code>customer_id</code>.</li>
    <li>Calculate the total transaction <code>amount</code> for each <code>branch</code> using <code>SUM()</code>.</li>
    <li>Use <code>GROUP BY</code> to organize the results by branch.</li>
    <li>Run the query using <code>pd.read_sql_query()</code> with <code>conn</code>.</li>
    <li>Display the results with one row per branch.</li>
  </ol>

</div>

<div style="font-family: 'Times New Roman', serif; font-size: 18px; line-height: 1.6;">

  <h2 style="color: #006699; font-weight: bold;">Key Takeaways</h2>
  <ul>
    <li><strong>SELECT</strong> asks for columns; <strong>WHERE</strong> filters rows; <strong>ORDER BY</strong> sorts.</li>
    <li><strong>GROUP BY</strong> + an aggregate is a pivot table in text form; <strong>HAVING</strong> filters the groups.</li>
    <li><strong>JOIN</strong> connects tables through a shared key: use <strong>LEFT JOIN</strong> when you must not lose rows.</li>
    <li>Loading a CSV with <code>to_sql()</code> and querying with <code>read_sql_query()</code> is the same pattern for every dataset.</li>
  </ul>

  <h2 style="color: #006699;">Query order to remember</h2>
  <pre style="background: #f4f4f4; padding: 10px; border-left: 4px solid #006699;">
SELECT ... FROM ... [JOIN ... ON ...] WHERE ... GROUP BY ... HAVING ... ORDER BY ... LIMIT ...</pre>

</div>

In [25]:
# Always close the connection when you are done
conn.close()


<div style="font-family: 'Times New Roman', serif; font-size: 18px; line-height: 1.6;">

<h2 style="color: #006699; font-weight: bold;">
📝 Week 09 Blog Activity: SQL in Python
</h2>

<p>
Complete all <strong>7 Student Practice Tasks</strong>
from the Week 09 learning materials using Jupyter Notebook.
</p>

<h3 style="color: #006699;">Student Practice Tasks</h3>

<p><strong>1. SELECT: Sales Data</strong></p>
<p>
Display sale_date, product, and price from the sales table.
</p>

<p><strong>2. WHERE: Human Resources</strong></p>
<p>
Find employees in Chicago with more than 10 years of experience
using WHERE and AND.
</p>

<p><strong>3. ORDER BY: Real Estate</strong></p>
<p>
Display the three largest properties by square footage
using ORDER BY and LIMIT.
</p>

<p><strong>4. GROUP BY: Marketing</strong></p>
<p>
Calculate total weekly impressions using SUM() and GROUP BY.
</p>

<p><strong>5. HAVING: Restaurant</strong></p>
<p>
Find dates when total restaurant sales exceeded $400.
</p>

<p><strong>6. Aggregate Functions: Healthcare</strong></p>
<p>
Find the average patient age and longest waiting time
for each doctor.
</p>

<p><strong>7. JOIN: Banking</strong></p>
<p>
Join customer and transaction tables to calculate
total transaction amounts by branch.
</p>

<h3 style="color: #006699;">📤 Submission Instructions</h3>

<p><strong>Step 1:</strong> Complete all seven Student Practice Tasks in Jupyter Notebook.</p>

<p><strong>Step 2:</strong> Run all code cells and verify the results.</p>

<p><strong>Step 3:</strong> Save the completed notebook as an .ipynb file.</p>

<p><strong>Step 4:</strong> Upload the file to your GitHub repository.</p>

<p><strong>Step 5:</strong> Share the GitHub file link in your Week 09 blog post.</p>

<p>
<strong>Reminder:</strong> Ensure your GitHub link is accessible
and all seven practice tasks are completed.
</p>

</div>

# **Student Practice Tasks**

In [1]:
import os
print(os.getcwd())
print(os.listdir())

C:\Users\sandh\OneDrive\Desktop\simran
['.ipynb_checkpoints', 'eSewa.docx', 'Extra credit .ipynb', 'frost.txt', 'OneDrive_1_10-25-2026', 'Untitled.ipynb', 'Untitled1.ipynb', 'Week 03-Python.png', 'Week 1 discussion.docx', 'Week_09_SQL_Assignment.ipynb']

In [2]:
os.chdir('OneDrive_1_10-25-2026')
print(os.listdir())

['bank_customers.csv', 'bank_transactions.csv', 'clinic_visits.csv', 'hr_employees.csv', 'marketing_campaigns.csv', 'my_data.db', 'realestate_listings.csv', 'restaurant_orders.csv', 'sales.csv']

In [3]:
import sqlite3
import pandas as pd

conn = sqlite3.connect('my_data.db')
cursor = conn.cursor()

In [4]:
pd.read_csv('sales.csv').to_sql('sales', conn, if_exists='replace', index=False)
pd.read_csv('hr_employees.csv').to_sql('hr_employees', conn, if_exists='replace', index=False)
pd.read_csv('realestate_listings.csv').to_sql('realestate_listings', conn, if_exists='replace', index=False)
pd.read_csv('marketing_campaigns.csv').to_sql('marketing_campaigns', conn, if_exists='replace', index=False)
pd.read_csv('restaurant_orders.csv').to_sql('restaurant_orders', conn, if_exists='replace', index=False)
pd.read_csv('clinic_visits.csv').to_sql('clinic_visits', conn, if_exists='replace', index=False)
pd.read_csv('bank_customers.csv').to_sql('bank_customers', conn, if_exists='replace', index=False)
pd.read_csv('bank_transactions.csv').to_sql('bank_transactions', conn, if_exists='replace', index=False)

45

# **Task 1: SELECT - Sales Data**

In [5]:
pd.read_sql_query("""
SELECT sale_date, product, price
FROM sales
""", conn)

    sale_date     product   price
0    9/1/2026      Laptop  999.99
1    9/1/2026       Mouse   24.99
2    9/2/2026     Monitor  199.99
3    9/2/2026    Keyboard   49.99
4    9/3/2026      Laptop  999.99
5    9/3/2026  Headphones   79.99
6    9/4/2026       Mouse   24.99
7    9/4/2026     Monitor  199.99
8    9/5/2026      Laptop  999.99
9    9/5/2026    Keyboard   49.99
10   9/6/2026  Headphones   79.99
11   9/6/2026      Tablet  449.99
12   9/7/2026       Mouse   24.99
13   9/7/2026      Tablet  449.99
14   9/8/2026     Monitor  199.99
15   9/8/2026      Laptop  999.99
16   9/9/2026    Keyboard   49.99
17   9/9/2026  Headphones   79.99
18  9/10/2026      Tablet  449.99
19  9/10/2026       Mouse   24.99

# **Task 2: WHERE - Human Resources**

In [6]:
pd.read_sql_query("""
SELECT *
FROM hr_employees
WHERE city = 'Chicago' AND years_experience > 10
""", conn)

   employee_id  name  department     city  salary  years_experience full_time
0         1027  Lily  Operations  Chicago   56000                17       Yes

# **Task 3: ORDER BY - Real Estate**

In [10]:
pd.read_sql_query("""
SELECT *
FROM realestate_listings
ORDER BY sqft DESC
LIMIT 3
""", conn)

,listing_id,neighborhood,property_type,bedrooms,sqft,list_price,days_on_market
0,204,Riverside,Condo,5,3736,979000,71
1,206,Maple Grove,Condo,5,3693,1001000,52
2,209,Maple Grove,House,1,3499,661000,116

In [8]:
pd.read_csv('realestate_listings.csv').columns

Index(['listing_id', 'neighborhood', 'property_type', 'bedrooms', 'sqft',
       'list_price', 'days_on_market'],
      dtype='str')

# **Task 4: GROUP BY — Marketing**

In [11]:
pd.read_csv('marketing_campaigns.csv').columns

Index(['record_id', 'campaign', 'channel', 'week', 'impressions', 'clicks',
       'spend', 'conversions'],
      dtype='str')

In [12]:
pd.read_sql_query("""
SELECT week, SUM(impressions) AS total_impressions
FROM marketing_campaigns
GROUP BY week
""", conn)

   week  total_impressions
0     1             181454
1     2              74972
2     3             193242
3     4             180795
4     5             264615
5     6             229892
6     7             235470
7     8             253354

# **Task 5: HAVING — Restaurant**

In [13]:
pd.read_csv('restaurant_orders.csv').columns

Index(['order_id', 'order_date', 'menu_item', 'server', 'table_size',
       'order_total', 'tip'],
      dtype='str')

In [14]:
pd.read_sql_query("""
SELECT order_date, SUM(order_total) AS total_sales
FROM restaurant_orders
GROUP BY order_date
HAVING SUM(order_total) > 400
""", conn)

   order_date  total_sales
0  2026-10-02       492.14
1  2026-10-05       850.10
2  2026-10-07       415.94
3  2026-10-12       633.98

# **Task 6: Aggregate Functions — Healthcare**

In [15]:
pd.read_csv('clinic_visits.csv').columns

Index(['visit_id', 'visit_date', 'department', 'doctor', 'patient_age',
       'wait_minutes', 'visit_cost'],
      dtype='str')

In [16]:
pd.read_sql_query("""
SELECT doctor,
       AVG(patient_age) AS average_age,
       MAX(wait_minutes) AS longest_wait
FROM clinic_visits
GROUP BY doctor
""", conn)

      doctor  average_age  longest_wait
0  Dr. Adams    47.000000            75
1   Dr. Chen    57.600000            50
2  Dr. Gomez    33.666667            75
3  Dr. Patel    45.375000            59
4  Dr. Scott    44.857143            63

# **Task 7: JOIN — Banking**

In [17]:
print(pd.read_csv('bank_customers.csv').columns)
print(pd.read_csv('bank_transactions.csv').columns)

Index(['customer_id', 'customer_name', 'account_type', 'branch', 'join_year'], dtype='str')
Index(['transaction_id', 'customer_id', 'transaction_date', 'transaction_type',
       'amount'],
      dtype='str')

In [18]:
pd.read_sql_query("""
SELECT bank_customers.branch,
       SUM(bank_transactions.amount) AS total_amount
FROM bank_customers
JOIN bank_transactions
ON bank_customers.customer_id = bank_transactions.customer_id
GROUP BY bank_customers.branch
""", conn)

      branch  total_amount
0    Airport      15177.98
1    Main St       3581.19
2  Northgate      19546.49
3   Westside      13996.30